# Generated by Django 4.2.1 on 2023-05-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurfWallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
