# Generated by Django 4.2.1 on 2023-05-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurfWallet', '0004_spot_creator_surfboard_fins_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='started_surfing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surfing_level',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'First time'), (2, 'Beginner'), (3, 'Medium-Beginner'), (4, 'Medium'), (5, 'Medium-Advanced'), (6, 'Advanced'), (7, 'Advanced-Pro'), (8, 'Pro')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
